Repository modmopet/modmopet, pull requests merged in 2023-06, with the labels that each got.

#34 fix: use path.join to get the correct path on linux
  lib/src/service/filesystem/emulator/ryujinx_filesystem.dart
  lib/src/service/filesystem/emulator/yuzu_filesystem.dart
Labels: bug

#36 fix: use path.join to get the correct path on linux
  lib/src/service/filesystem/emulator/ryujinx_filesystem.dart
  lib/src/service/filesystem/emulator/yuzu_filesystem.dart
Labels: bug

#37 ci: add better changelog to the releases
  .github/workflows/release.yml
Labels: enhancement

#38 fix: bug error when any game was never got launched on emulator
  lib/src/service/filesystem/emulator/ryujinx_filesystem.dart
  lib/src/service/filesystem/emulator/yuzu_filesystem.dart
Labels: bug

#43 fix: add alternative possible files for yuzu
  lib/src/service/filesystem/emulator/yuzu_filesystem.dart
Labels: bug

#44 Fix: Missed await for deleting the folder
  lib/src/entity/git_source.dart
Labels: bug

#45 feat: add auto-updater
  .github/workflows/release.yml
  .gitignore
  lib/main.dart
  lib/src/app.dart
  lib/src/entity/git_source.dart
  lib/src/provider/game_list_provider.dart
  lib/src/screen/mods/mods_view.dart
  lib/src/service/github/github.dart
  lib/src/widgets/mm_layout.dart
  linux/packaging/appimage/make_config.yaml
  linux/packaging/deb/make_config.yaml
  macos/packaging/dmg/make_config.yaml
  pubspec.lock
  pubspec.yaml
  windows/packaging/msix/make_config.yaml
Labels: feature
